apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-exam-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-exam
  template:
    metadata:
      labels:
        app: spring-exam
    spec:
      containers:
        - name: spring-exam
          image: grewu/spring-exam-app:1.0.0-24
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 9011
