apiVersion: v1
kind: Service
metadata:
  name: spring-exam-service
  labels:
    app: spring-exam
spec:
  selector:
    app: spring-exam

  ports:
    - port: 8181
      targetPort: 8111

  type: NodePort
